name: Deploy PR preview

on:
  workflow_run:
    workflows: ["Build PR preview"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download Pages artifact from triggering run
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

